info:
  namespace: "rank"
font_images:
  wemmbu:
    show_in_gui: false
    path: wemmbu.png
    scale_ratio: 9
    y_position: 8
  wemmbu_plus:
    show_in_gui: false
    path: wemmbu_plus.png
    scale_ratio: 9
    y_position: 8
  theo:
    show_in_gui: false
    path: theo.png
    scale_ratio: 9
    y_position: 8
  flamefrags:
    show_in_gui: false
    path: flamefrags.png
    scale_ratio: 9
    y_position: 8
  manepear:
    show_in_gui: false
    path: manepear.png
    scale_ratio: 9
    y_position: 8
  minutetech:
    show_in_gui: false
    path: minutetech.png
    scale_ratio: 9
    y_position: 8
  wraith:
    show_in_gui: false
    path: wraith.png
    scale_ratio: 9
    y_position: 8
